Simulink.defineIntEnumType( 'CELC_E_UsageMod', ...
   {'CELC_E_UsageMod_Abandoned', 'CELC_E_UsageMod_Inactive', 'CELC_E_UsageMod_Active', 'CELC_E_UsageMod_Driving'}, ...
   [0, 1, 2, 3], ...
   'Description', 'Type definition of CELC_E_UsageMod.', ...
   'DataScope', 'Auto',...
   'AddClassNameToEnumNames', false);


Simulink.defineIntEnumType( 'CELC_E_EgyLoadFctSts', ...
   {'CELC_E_EgyLoadFctSts_Active', 'CELC_E_EgyLoadFctSts_Inactive'}, ...
   [0, 1], ...
   'Description', 'Type definition of CELC_E_EgyLoadFctSts.', ...
   'DataScope', 'Auto',...
   'AddClassNameToEnumNames', false);

