% -------------------------------------------------------------------
%  MATLAB file generated by Simulink.saveVars on 23-Jun-2016 17:49:58
%  MATLAB version: 8.2.0.701 (R2013b)
% -------------------------------------------------------------------
                                          

ASW_T_UBYTE = Simulink.AliasType;
ASW_T_UBYTE.Description = '';
ASW_T_UBYTE.DataScope = 'Auto';
ASW_T_UBYTE.HeaderFile = 'Rte_Type.h';
ASW_T_UBYTE.BaseType = 'uint8';

ASW_T_UINT16 = Simulink.AliasType;
ASW_T_UINT16.Description = '';
ASW_T_UINT16.DataScope = 'Auto';
ASW_T_UINT16.HeaderFile = 'Rte_Type.h';
ASW_T_UINT16.BaseType = 'uint16';

PASE_T_Boolean = Simulink.AliasType;
PASE_T_Boolean.Description = '';
PASE_T_Boolean.DataScope = 'Auto';
PASE_T_Boolean.HeaderFile = 'Rte_Type.h';
PASE_T_Boolean.BaseType = 'boolean';

PASE_T_uint8 = Simulink.AliasType;
PASE_T_uint8.Description = '';
PASE_T_uint8.DataScope = 'Auto';
PASE_T_uint8.HeaderFile = 'Rte_Type.h';
PASE_T_uint8.BaseType = 'uint8';

TPsrv_S_DetailedResult = Simulink.Bus;
TPsrv_S_DetailedResult.Description = '';
TPsrv_S_DetailedResult.DataScope = 'Auto';
TPsrv_S_DetailedResult.HeaderFile = 'Rte_Type.h';
TPsrv_S_DetailedResult.Alignment = -1;
saveVarsTmp{1} = Simulink.BusElement;
saveVarsTmp{1}.Name = 'AuthDiagLastReceivedIDE';
saveVarsTmp{1}.Complexity = 'real';
saveVarsTmp{1}.Dimensions = 4;
saveVarsTmp{1}.DataType = 'TPsrv_T_uint8';
saveVarsTmp{1}.Min = [];
saveVarsTmp{1}.Max = [];
saveVarsTmp{1}.DimensionsMode = 'Fixed';
saveVarsTmp{1}.SamplingMode = 'Sample based';
saveVarsTmp{1}.SampleTime = -1;
saveVarsTmp{1}.DocUnits = '';
saveVarsTmp{1}.Description = '';
saveVarsTmp{1}(2, 1) = Simulink.BusElement;
saveVarsTmp{1}(2, 1).Name = 'LastTPIndex';
saveVarsTmp{1}(2, 1).Complexity = 'real';
saveVarsTmp{1}(2, 1).Dimensions = 1;
saveVarsTmp{1}(2, 1).DataType = 'TPsrv_T_uint8';
saveVarsTmp{1}(2, 1).Min = [];
saveVarsTmp{1}(2, 1).Max = [];
saveVarsTmp{1}(2, 1).DimensionsMode = 'Fixed';
saveVarsTmp{1}(2, 1).SamplingMode = 'Sample based';
saveVarsTmp{1}(2, 1).SampleTime = -1;
saveVarsTmp{1}(2, 1).DocUnits = '';
saveVarsTmp{1}(2, 1).Description = '';
saveVarsTmp{1}(3, 1) = Simulink.BusElement;
saveVarsTmp{1}(3, 1).Name = 'Client';
saveVarsTmp{1}(3, 1).Complexity = 'real';
saveVarsTmp{1}(3, 1).Dimensions = 1;
saveVarsTmp{1}(3, 1).DataType = 'Enum: TPsrv_E_Client';
saveVarsTmp{1}(3, 1).Min = [];
saveVarsTmp{1}(3, 1).Max = [];
saveVarsTmp{1}(3, 1).DimensionsMode = 'Fixed';
saveVarsTmp{1}(3, 1).SamplingMode = 'Sample based';
saveVarsTmp{1}(3, 1).SampleTime = -1;
saveVarsTmp{1}(3, 1).DocUnits = '';
saveVarsTmp{1}(3, 1).Description = '';
saveVarsTmp{1}(4, 1) = Simulink.BusElement;
saveVarsTmp{1}(4, 1).Name = 'ScenRetryNb';
saveVarsTmp{1}(4, 1).Complexity = 'real';
saveVarsTmp{1}(4, 1).Dimensions = 1;
saveVarsTmp{1}(4, 1).DataType = 'TPsrv_T_uint8';
saveVarsTmp{1}(4, 1).Min = [];
saveVarsTmp{1}(4, 1).Max = [];
saveVarsTmp{1}(4, 1).DimensionsMode = 'Fixed';
saveVarsTmp{1}(4, 1).SamplingMode = 'Sample based';
saveVarsTmp{1}(4, 1).SampleTime = -1;
saveVarsTmp{1}(4, 1).DocUnits = '';
saveVarsTmp{1}(4, 1).Description = '';
saveVarsTmp{1}(5, 1) = Simulink.BusElement;
saveVarsTmp{1}(5, 1).Name = 'FailureBits';
saveVarsTmp{1}(5, 1).Complexity = 'real';
saveVarsTmp{1}(5, 1).Dimensions = 1;
saveVarsTmp{1}(5, 1).DataType = 'TPsrv_T_Failure';
saveVarsTmp{1}(5, 1).Min = [];
saveVarsTmp{1}(5, 1).Max = [];
saveVarsTmp{1}(5, 1).DimensionsMode = 'Fixed';
saveVarsTmp{1}(5, 1).SamplingMode = 'Sample based';
saveVarsTmp{1}(5, 1).SampleTime = -1;
saveVarsTmp{1}(5, 1).DocUnits = '';
saveVarsTmp{1}(5, 1).Description = '';
saveVarsTmp{1}(6, 1) = Simulink.BusElement;
saveVarsTmp{1}(6, 1).Name = 'FirstScenStepFailed';
saveVarsTmp{1}(6, 1).Complexity = 'real';
saveVarsTmp{1}(6, 1).Dimensions = 1;
saveVarsTmp{1}(6, 1).DataType = 'TPsrv_T_uint8';
saveVarsTmp{1}(6, 1).Min = [];
saveVarsTmp{1}(6, 1).Max = [];
saveVarsTmp{1}(6, 1).DimensionsMode = 'Fixed';
saveVarsTmp{1}(6, 1).SamplingMode = 'Sample based';
saveVarsTmp{1}(6, 1).SampleTime = -1;
saveVarsTmp{1}(6, 1).DocUnits = '';
saveVarsTmp{1}(6, 1).Description = '';
saveVarsTmp{1}(7, 1) = Simulink.BusElement;
saveVarsTmp{1}(7, 1).Name = 'FirstScenStepFailedResult';
saveVarsTmp{1}(7, 1).Complexity = 'real';
saveVarsTmp{1}(7, 1).Dimensions = 1;
saveVarsTmp{1}(7, 1).DataType = 'TPsrv_T_uint8';
saveVarsTmp{1}(7, 1).Min = [];
saveVarsTmp{1}(7, 1).Max = [];
saveVarsTmp{1}(7, 1).DimensionsMode = 'Fixed';
saveVarsTmp{1}(7, 1).SamplingMode = 'Sample based';
saveVarsTmp{1}(7, 1).SampleTime = -1;
saveVarsTmp{1}(7, 1).DocUnits = '';
saveVarsTmp{1}(7, 1).Description = '';
TPsrv_S_DetailedResult.Elements = saveVarsTmp{1};
clear saveVarsTmp;

TPsrv_T_Failure = Simulink.AliasType;
TPsrv_T_Failure.Description = '';
TPsrv_T_Failure.DataScope = 'Auto';
TPsrv_T_Failure.HeaderFile = 'Rte_Type.h';
TPsrv_T_Failure.BaseType = 'uint16';

TPsrv_T_uint8 = Simulink.AliasType;
TPsrv_T_uint8.Description = '';
TPsrv_T_uint8.DataScope = 'Auto';
TPsrv_T_uint8.HeaderFile = 'Rte_Type.h';
TPsrv_T_uint8.BaseType = 'uint8';

